---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: quote
spec:
  prefix: /quote/
  service: quote
  bypass_auth: true
  labels:
    ambassador: 
      - request_label_group: 
        - x-ambassador-test-allow: 
          header : "x-ambassador-test-allow"
  #// rate_limits: 
  #//  - descriptor: A test case 
  #//    header: 
  #//     - "x-ambassador-test-allow"
---
apiVersion: v1
kind: Service
metadata:
  name: quote
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: quote-backend
      prefix: /
      service: quote:5000
      ---
      apiVersion: ambassador/v2
      kind: Mapping
      name: quote-backend
      prefix: /backend/
      service: quote
      rate_limits:
        - descriptor: A test case
          headers:
            - "x-ambassador-test-allow"
    a8r.io/description: 'Quote of the moment service'
    a8r.io/owner: 'No owner'
    a8r.io/chat: '#ambassador'
    a8r.io/bugs: 'https://github.com/datawire/qotm/issues'
    a8r.io/documentation: 'https://github.com/datawire/qotm/blob/master/README.md'
    a8r.io/repository: 'https://github.com/datawire/qotm'
    a8r.io/support: 'http://a8r.io/Slack'
    a8r.io/runbook: 'https://github.com/datawire/qotm/blob/master/README.md'
    a8r.io/incidents: 'https://github.com/datawire/qotm/issues'
    a8r.io/dependencies: 'None'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: quote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: backend
          image: docker.io/datawire/quote:0.4.1
          ports:
            - name: http
              containerPort: 8080
